min_time: '15:45'
max_time: '18:00'
keywords:
  - algorithms
  - arduino
  - back end development
  - big data
  - computer science
  - darpa
  - elm language
  - ember js
  - front end development
  - functional programming
  - game development
  - haskell
  - information security
  - investing
  - javascript
  - jsconf
  - linux
  - lua language
  - machine learning
  - node js
  - procedural generation
  - programming
  - robotics
  - ruby language -pokemon -knights
  - siggraph
  - speedrun
  - table tennis
  - talks at google
  - tool assisted speedrun
  - vim editor
  - web development